### ISSUE TITLE
RHEL9 vmimport support

### ISSUE THREAD

**Issue by midhuhk** [awsdocs/vm-import-export-user-guide#10]

**Comment by JRNC** [comment]
Our organization has also been waiting on RHEL 9 import support from the AWS import service. Please note that this affects both being able to import custom AMIs and being able to restore backups into AWS for disaster recovery purposes (which is quite popular amongst many enterprise customers). Is there any ETA for this support?

**Comment by jmjesse** [comment]
Apologies for the delayed response here! The team doesn't currently have any dates to share. You can monitor for updates to our supported operating systems on this page:
https://docs.aws.amazon.com/vm-import/latest/userguide/prerequisites.html#vmimport-operating-systems-linux
