### ISSUE TITLE
import plugin throw error 400 saying InvalidParameterValue: The specified KMS key is not accessible

### ISSUE THREAD

**Issue by rajbir1982** [awsdocs/vm-import-export-user-guide#9]
2 days back everything was working. but now it started giving this error. i am able to reproduce same error in dev environment. for testing i created a s3 without encryption and new kms key. but i am getting same error there.

aws ec2 import-image --description "123" --encrypted --kms-key-id arn:aws:kms:us-east-1:123456789:key/abc-efg-hij-klm-nop-xyz --disk-containers Format=ova,UserBucket="{S3Bucket=<mybucket>,S3Key=<my ova file in s3>}"

An error occurred (InvalidParameterValue) when calling the ImportImage operation: The specified KMS key is not accessible. If this is a default EBS CMK, please retry your request without specifying the key explicitly

**Comment by jmjesse** [comment]
Hi,

Thanks for reaching out to AWS Documentation. I have checked into this issue internally and can confirm that the behavior should be resolved on our side with the service. Please let me know if the issue persists, or feel free to close this out.
